---
- name: Deploy Wazuh Agent on all Linux hosts
  hosts: all
  become: true
  vars:
    wazuh_manager_ip: "192.168.1.36"    # Replace with your Wazuh manager IP
    wazuh_repo_url: "https://packages.wazuh.com/4.x/apt/"

  tasks:
    - name: Install required dependencies
      ansible.builtin.apt:
        name:
          - curl
          - apt-transport-https
          - lsb-release
        state: present
        update_cache: yes

    - name: Add Wazuh GPG key (bypass HTTPS cert issues)
      ansible.builtin.apt_key:
        url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
        state: present
        validate_certs: no

    - name: Add Wazuh repository
      ansible.builtin.apt_repository:
        repo: "deb {{ wazuh_repo_url }} stable main"
        state: present

    - name: Install Wazuh agent
      ansible.builtin.apt:
        name: wazuh-agent
        state: present
        update_cache: yes

    - name: Configure Wazuh agent manager
      ansible.builtin.lineinfile:
        path: /var/ossec/etc/ossec.conf
        regexp: "<address>.*</address>"
        line: "<address>{{ wazuh_manager_ip }}</address>"

    - name: Enable and start Wazuh agent service
      ansible.builtin.systemd:
        name: wazuh-agent
        enabled: yes
        state: started
